### ISSUE TITLE
Auto submit received OTP(Enable Auto submit OTP)

### ISSUE THREAD

**Issue by Mukeshkrjha** [crashlytics/digits-android#100]
Hi There,

OTP sent digits is read automatically that is great feature but along with that I want to submit OTP automatically as well can we do this using Digits-Android? As it is trend these day and convenient for user as well.

If yes then please explain which version of Digits-Android support it and how to do this?

Please reply ASAP as my development depends on this.

Thanks  

Mukesh Jha

**Comment by mikebonnell** [comment]
Hey Mukesh,

Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)

**Comment by Mukeshkrjha** [comment]
That's OK Mike,

Questions remain same, can we auto submit OTP with Firebase Phone Authentication?

if yes please share some reference.

Thanks

**Comment by mikebonnell** [comment]
Yes, check out the section called "onVerificationCompleted" in Firebase's site: https://firebase.google.com/docs/auth/android/phone-auth
