### ISSUE TITLE
Shouldn't DigitsSession#getId() be ID of session, not userId tied to current session?

### ISSUE THREAD

**Issue by daisy1754** [crashlytics/digits-android#35]
It seems DigitsSession uses `ID of user` as `ID of session`. 
https://github.com/twitter/digits-android/blob/76a1c0bdf8a885fe17029dd2b1cdeda28d105459/digits/src/main/java/com/digits/sdk/android/DigitsSession.java

Is it correct behaviour? I'd assume a single digits user can have multiple sessions. 

For reference, [ios sdk's DGTSession seems exposing `userId` property](https://dev.twitter.com/twitter-kit/ios-reference/dgtsession).

**Comment by daisy1754** [comment]
Created #36 to add `Session#getUserId()` method (currently alias to `Session#getId()`)

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
