### ISSUE TITLE
No callback mechanism for upload contact permission dialog

### ISSUE THREAD

**Issue by daisy1754** [crashlytics/digits-android#37]
https://docs.fabric.io/android/digits/find-friends.html

> The first time startContactsUpload is called a dialog requesting permission to upload the user’s address book will be displayed.

This is handled by following code
https://github.com/twitter/digits-android/blob/33dd49d1f235156c5081f1a3178d23263ea0f20b/digits/src/main/java/com/digits/sdk/android/ContactsActivityDelegateImpl.java

```
    protected void setUpNotNowButton(Button button) {
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                activity.finish();
            }
        });
    }

    protected void setUpOkayButton(Button button) {
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                controller.startUploadService(activity);
                activity.finish();
            }
        });
    }
```

... as we can see, there is no mechanism for client app to know user click button, and which option is selected.

Once client app calls `ContactClients#startContactsUpload`, digits SDK may or may not start `ContactsActivity` and user can take multiple options (e.g., press back, press "not now", press "Okay"). 
Is it possible to implement some sort of callback so client app can implement proper user experience?

**Comment by daisy1754** [comment]
Given digits should show UI to ask user's consent before uploading contact, I think SDK should also request Runtime permission on client app's behave. Also it's hard for client app to request contact permission at appropriate timing because of https://github.com/twitter/digits-android/issues/37

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
