### ISSUE TITLE
Digits SDK doesn't handle Android M runtime permission

### ISSUE THREAD

**Issue by daisy1754** [crashlytics/digits-android#38]
Android M introduced runtime permission model for some permissions, including access to contact list.

It doesn't seem digits sdk has code to handle those permissions. On the other hand, these javadocs in `ContactsClient.java` seems quite confusing as it sounds sdk takes care of Android runtime permissions.

```
     * First checks if user previously gave permission to upload contacts. If not, shows
     * dialog requesting permission to upload users contacts. If permission granted start
     * background service to upload contacts. Otherwise, do nothing.
```

**Comment by efrohnhoefer** [comment]
So permission in this context is granting Twitter the permission to upload contacts and perform matching based on contacts. This javadoc was written before Android M was released. Currently developers have to ask for the system permission before starting contact upload. This will likely change in a future release to mirror iOS. On iOS we only ask to the system permission once user has granted Twitter permission to upload contacts.

**Comment by YashalShakti** [comment]
@efrohnhoefer This also applies to the code/phone number auto-fill permissions. It'll be convenient to have this integrated.

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
