### ISSUE TITLE
UPLOAD_FAILED intent should contain extra to represent a cause of failure

### ISSUE THREAD

**Issue by daisy1754** [crashlytics/digits-android#40]
Currently, [UPLOAD_FAILED intent doesn't contain any extra information](https://github.com/twitter/digits-android/blob/33dd49d1f235156c5081f1a3178d23263ea0f20b/digits/src/main/java/com/digits/sdk/android/ContactsUploadService.java#L143). As a result, developer cannot decide whether what action to take.

I propose adding `EXTRA_FAILURE_REASON` so developer can distinguish following cases
- transient network failure / digits server unstable -> developer should retry later
- developer's configuration error (e.g., invalid api key) -> developer should fix configuration
- [user has zero contact](https://github.com/twitter/digits-android/blob/33dd49d1f235156c5081f1a3178d23263ea0f20b/digits/src/main/java/com/digits/sdk/android/ContactsUploadService.java#L111)  (first of all, should this be result in UPLOAD_FAILED?) -> maybe developer can choose to ignore

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
