### ISSUE TITLE
How to change country code spinner expanded style in sdk 14?

### ISSUE THREAD

**Issue by taylor19882002** [crashlytics/digits-android#42]
Hi, I want change spinner expanded style such as text color and list background color. I have try to set  value -14 style dropDownListViewStyle and spinnerDropDownItemStyle but not work.

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
