### ISSUE TITLE
Digits.getInstance().getContactsClient().lookupContactMatches not working

### ISSUE THREAD

**Issue by nightbear1009** [crashlytics/digits-android#61]
hi,
I use the sample code and login with digit successful and upload my concact successfully
, but Digits.getInstance().getContactsClient().lookupContactMatches always return null, please help me. thx 
devcice : htcM9
android ver: 6.0

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
