### ISSUE TITLE
lookupContactMatches - not returning users that have previously signed in app and uploaded contacts

### ISSUE THREAD

**Issue by Trollologic** [crashlytics/digits-android#62]
Digits.getInstance().getContactsClient().lookupContactMatches - only returns contacts that have signed in app after us. For example if we have two users (user1 - first signed, user2 - second signed in app) **user1** - will receive data about user2, but **user2** won't receive data about user1

Digits.getInstance().getContactsClient().lookupContactMatches(null, null,
                new ContactsCallback<Contacts>() {

```
                @Override
                public void success(Result<Contacts> result) {
                    if (result.data.users != null) {
                        // Process data
                          Log.i(TAG, "DigitsUser download success "+result.data.users.size());
                    }else {
                          Log.i(TAG, "DigitsUser null");
                    }
                }

                @Override
                public void failure(TwitterException exception) {
                    UserLog.i(TAG, "DigitsUser download failure");
                }
            });
```

**Do you know how could i fix this issue?**

**Comment by shubhambansal** [comment]
@Trollologic : How are you mapping returning digit id's to their respective contact number?
I don't see any phone number field in Contacts.
