### ISSUE TITLE
Theming - Setting logo with vector drawable Android lower than API 21

### ISSUE THREAD

**Issue by dsdebastiani** [crashlytics/digits-android#64]
Support vectorDrawables using Support Lib for Android lower than API 21.

Please read the full issue in TwitterDeveloper:
https://twittercommunity.com/t/android-theming-setting-logo-with-vector-drawable/67521

**Comment by dsdebastiani** [comment]
I think that I found a simple solution, but I didn't try yet.

The Support Lib docs say that all ```ImageView``` instances will be wrapped with ```AppCompatImageView``` if the app is using them AppCompat Suport Lib. It also say that, in this case, is not necessary a changes to load a vector if you use the ```setImageResource()``` method.

So, a possible solution to create a compat logo for Digits are:
Changes in ```ThemeUtils.java```:```getLogoResID``` instead ```getLogoDrawable```
```
    static int getLogoResId(Theme theme) {
        final TypedValue typedValue = new TypedValue();
        final int[] drawableAttr = new int[]{R.attr.dgts__logoDrawable};
        final int indexOfAttr = 0;
        final TypedArray a = theme.obtainStyledAttributes(typedValue.data, drawableAttr);
        return a.getResourceId(indexOfAttr, 0);
    }
```
If developer hasn't defined the ```dgts__logoDrawable``` attributhe in theme, the method will return ```0```, so we need a another change in ```LogoImageView.java```:```initImageView``` method:
```
    void initImageView(Context context) {
       final int logoResId = ThemeUtils.getLogoResId(context.getTheme());
        if (logoDrawable != 0) {
            setVisibility(View.VISIBLE);
            setImageResource(logoResId);
        } else {
            setVisibility(View.GONE);
        }
    }
```

I think this solve, but maybe wont be a good solution, because the method ```setImageResource()``` can cause a latency hiccup, accordingly with the [doc](https://developer.android.com/reference/android/widget/ImageView.html?utm_campaign=android_launch_supportlibrary23.2_022216&utm_source=anddev&utm_medium=blog#setImageResource%28int%29).

Another solution, but more complex, would be verify if the attribute ```dgts__logoDrawable``` is a vector (I don't know how do taht), verify if app is using appCompat ```if (imageView instanceof AppCompatImageView)```, verify the api level <21 and use the VectorDrawableCompat:
```
Drawable logoDrawable = VectorDrawableCompat.create(getResources(), R.drawable.vector_drawable, getTheme());
setImageDrawable(logoDrawable);
```

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
