### ISSUE TITLE
Modify visibility of classes to properly implement ApiInterface

### ISSUE THREAD

**Issue by dustedrob** [crashlytics/digits-android#71]
I'm trying out the new Sandbox mode but to properly set a SandBoxConfig with a custom ApiInterface it is necessary to implement the following methods which requiere classes that are not visible:

`@FormUrlEncoded
        @POST("/1/sdk/login")
        void auth(@Field("x_auth_phone_number") String phoneNumber,
                  @Field("verification_type") String verificationType,
                  @Field("lang") String lang,
                  Callback<AuthResponse> cb);`

`@Override
        public void login(@Field("login_verification_request_id") String requestId, @Field("login_verification_user_id") long userId, @Field("login_verification_challenge_response") String code, Callback<DigitsSessionResponse> cb)`

`@Override
        public void verifyPin(@Field("login_verification_request_id") String requestId, @Field("login_verification_user_id") long userId, @Field("pin") String pin, Callback<DigitsSessionResponse> cb)`

`@Override
        public void email(@Field("email_address") String email, Callback<DigitsSessionResponse> cb)`

`@Override
        public UploadResponse upload(@Body Vcards vcards) 
`

The  classes that need to be exposed are:

DigitsSessionResponse
AuthResponse
Vcards

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
