### ISSUE TITLE
send confirmation code fail in case mobile Language Arabic

### ISSUE THREAD

**Issue by mohamedhamada1** [crashlytics/digits-android#75]
Logcat message  
E/Digits: HTTP Error: Unexpected char 0x627 at 20 in header value: Digits/1.10.3.111 ( اي خدمة; Android 5.1.1), API Error: 0, User Message: Try Again

I use string file for arabic language with arabic app name 
<string name="app_name">اي خدمة</string>
when remove this line work fine 
any work around ?

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
