### ISSUE TITLE
Error message when entering wrong number of digits in the confirmation code only works for < 6

### ISSUE THREAD

**Issue by nicolasreich** [crashlytics/digits-android#76]
Hi,

It's a small issue I noticed today: when entering <6 digits for the confirmation code, the error message reads something like "wrong number of digits" whereas for >6 it reads "wrong code". It bugged me, so I figured I'd notify you. If it is something already known I apologise for the disturbance.

**Comment by mikebonnell** [comment]
Thanks for sharing this @nicolasreich, will look into a better error message in this case.
