### ISSUE TITLE
Numbers start with 91(without country code) are not accepted.

### ISSUE THREAD

**Issue by jaydeepw** [crashlytics/digits-android#77]
In India, we do have numbers for example +91 91609.... where +91 is the country code and 91 is the beginning of the mobile number.  So even if I enter the number that starts with 91(country code excluded) digits doesnt let me proceed.

I dont want to give the exact number in public but we can assist in tracing this issue. You can contact me at jay@intouchapp.com or Ankit at ankit@intouchapp.com

**Comment by mikebonnell** [comment]
Thanks for reaching out on this @jaydeepw, please email the numbers hitting this issue into support(at)fabric(dot)io.

**Comment by jaydeepw** [comment]
Sent you an email with the same subject as the title of this issue.

**Comment by vishal901** [comment]
AuthConfig.Builder digitsAuthConfigBuilder = new AuthConfig.Builder()
                        .withAuthCallBack(callback)
                        .withPhoneNumber("+91" + 1234567890);

                Digits.authenticate(digitsAuthConfigBuilder.build());

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
