### ISSUE TITLE
Crash on Lenovo devices with Android 6.0

### ISSUE THREAD

**Issue by nmohideen** [crashlytics/digits-android#79]
On Digits 2.0.0 seeing this crash consistently on Android 6.0.

> Fatal Exception: java.lang.IllegalArgumentException: Unexpected char 0x00 at 1 in header name: CType
>        at okhttp3.Headers$Builder.checkNameAndValue(Unknown Source:275)
>        at okhttp3.Headers$Builder.set(Unknown Source:263)
>        at okhttp3.Request$Builder.header(Unknown Source:165)
>        at okhttp3.RealCall.getResponse(Unknown Source:213)
>        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(Unknown Source:198)
>        at com.twitter.sdk.android.core.internal.oauth.OAuthService$1.intercept(Unknown Source:64)
>        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(Unknown Source:187)
>        at okhttp3.RealCall.getResponseWithInterceptorChain(Unknown Source:41160)
>        at okhttp3.RealCall$AsyncCall.execute(Unknown Source:127)
>        at okhttp3.internal.NamedRunnable.run(Unknown Source:32)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>        at java.lang.Thread.run(Thread.java:818)

**Comment by vishal901** [comment]
used this update version solve this issue
 com.digits.sdk.android:digits:2.0.3@aar
