### ISSUE TITLE
Test Digits on the new Android Emulator

### ISSUE THREAD

**Issue by lawloretienne** [crashlytics/digits-android#81]
In the sign up flow it asks you to `Enter your phone number`

![screen shot 2016-10-05 at 5 20 37 pm](https://cloud.githubusercontent.com/assets/311187/19136265/15e47d7c-8b20-11e6-830f-9b1855d5bf7a.png)

Can you complete this flow using the Android Emulator? If so, what number do you have to enter here?

**Comment by efrohnhoefer** [comment]
You can enter your own mobile number. There is no requirement you receive an SMS on the device you are registering.
