### ISSUE TITLE
How to enter the OTP automatically

### ISSUE THREAD

**Issue by srinivas69** [crashlytics/digits-android#83]
How can I enter OTP automatically when the message is been received to my Mobile Number? I'm using Android 6.0 mobile?

**Comment by rashidckk** [comment]
Adding the permission below, in the AndroidManifest.xml, allows Digits to read the SMS pin therefore making the login process easier.
<uses-permission android:name="android.permission.RECEIVE_SMS"/>
Source: [https://docs.fabric.io/android/digits/sign-in-with-phone-number.html](Digit Docs)

**Comment by vishal901** [comment]
Adding run time permission,
<uses-permission android:name="android.permission.RECEIVE_SMS" />

OTP automatically when the message is been received to my Mobile Number.

**Comment by sdattatri** [comment]
I have added 
uses-permission android:name="android.permission.RECEIVE_SMS" in the manifest.
but I still find that the OTP screen expects me to enter the OTP manually.  What am I doing wrong?

**Comment by daupawar** [comment]
Request permission in activity inside onCreate()

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
