### ISSUE TITLE
Message not read automatically

### ISSUE THREAD

**Issue by manish-dev-28** [crashlytics/digits-android#84]
I have added the receive_sms permission but OTP not filled automatically

**Comment by vishal901** [comment]
Adding run time permission,

uses-permission android:name="android.permission.RECEIVE_SMS"

OTP automatically when the message is been received to my Mobile Number.

**Comment by daupawar** [comment]
Add these two permissions in manifest file
```
 <uses-permission android:name="android.permission.RECEIVE_SMS"/>
    <uses-permission android:name="android.permission.READ_SMS"/>
```

and if you are testing on api level >= marshmellows

ask for same permissions, inside app

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
