### ISSUE TITLE
Exception in com.digits.sdk.android.SpacedEditText.setSelection

### ISSUE THREAD

**Issue by baole** [crashlytics/digits-android#85]
We have "java.lang.IndexOutOfBoundsException: setSpan (21 ... 21) ends beyond length 11" exception on our app. Here is stack track on Crashlytics

http://crashes.to/s/700a5f3336c

**Comment by dudadayan** [comment]
+1

**Comment by dudadayan** [comment]
+1

**Comment by heitorpr** [comment]
+1... waiting this fix

**Comment by MateusCarvalho** [comment]
+1

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
