### ISSUE TITLE
How to use .withCustomPhoneNumberScreen(ConfirmationCodeCallback c)?

### ISSUE THREAD

**Issue by abhiank** [crashlytics/digits-android#86]
Hello, 

In my app, I'm already taking the phone number as an input and am passing it as an argument in .withPhoneNumber("+919999999999"). However, since I am already taking the phone number I was trying to bypass the phone screen by Digits. How can I do that with the withCustomPhoneNumberScreen() method?

**Comment by VincentMolinie** [comment]
Did you find a way to use that function ?

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
