### ISSUE TITLE
Digits Activity still active after authentication version 2.0.4

### ISSUE THREAD

**Issue by inzi119** [crashlytics/digits-android#88]
I know this is said to be resolved. But still I have this issue. 
here is my code:

public class DigitsApp extends Application {

    // Note: Your consumer key and secret should be obfuscated in your source code before shipping.
    private static final String TWITTER_KEY = "MWZBkB6ftN1FjQaoAYizCuh8W";
    private static final String TWITTER_SECRET = "QtAjlU228kfLYZIx3qfNNNm1f4A7slVoVhOrU9GpVr2hTCMciP";
    private AuthCallback authCallback;

    @Override
    public void onCreate() {
        super.onCreate();
        TwitterAuthConfig authConfig = new TwitterAuthConfig(TWITTER_KEY, TWITTER_SECRET);
        Fabric.with(this, new TwitterCore(authConfig), new Digits.Builder().build());

        authCallback = new AuthCallback() {
            @Override
            public void success(DigitsSession session, String phoneNumber) {
                // Do something with the session
                Toast.makeText(getApplicationContext(), "sucess", Toast.LENGTH_LONG).show();
                
            }

            @Override
            public void failure(DigitsException exception) {
                // Do something on failure
            }
        };

        }
}

    public AuthCallback getAuthCallBack(){
        return authCallback;
    }

public class MainActivity extends AppCompatActivity {

    private AuthCallback authCallback;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        authCallback = ((DigitsApp)getApplication()).getAuthCallBack();

        DigitsAuthButton digitsButton = (DigitsAuthButton) findViewById(R.id.auth_button);
        digitsButton.setCallback(authCallback);

        digitsButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                AuthConfig.Builder authConfigBuilder = new AuthConfig.Builder()
                        .withAuthCallBack(authCallback)
                        .withPhoneNumber("+94");

                Digits.authenticate(authConfigBuilder.build());
            }
        });
    }

}

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
