### ISSUE TITLE
NullPointerException on DigitsApiClientManager

### ISSUE THREAD

**Issue by esdrasdl** [crashlytics/digits-android#89]
I'm not sure if you are still using it for issue tracker but I didn't found another way to report it.
I'm facing a crash on last version of Digits SDK. I used the version 2.0.2 and it worked fine. That crash happens on more often on Android 6 and Android 5.

`
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
       at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:772)
       at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:800)
       at com.digits.sdk.android.DigitsApiClientManager.getUserAuthClient(DigitsApiClientManager.java:53)
       at com.digits.sdk.android.AttributableInviteDownloadService.onHandleIntent(AttributableInviteDownloadService.java:55)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)`

You can check my setup below:

    ...
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'io.fabric.tools:gradle:1.22.1'
    }
    ...
    compile("com.crashlytics.sdk.android:answers:1.3.11@aar") {
        transitive = true;
    }
    
    compile("com.crashlytics.sdk.android:crashlytics:2.6.6@aar") {
        transitive = true;
    }

    compile("com.digits.sdk.android:digits:2.0.5@aar") {
        transitive = true;
    }

On my application class:
    
    TwitterAuthConfig authConfig = new TwitterAuthConfig(BuildConfig.TWITTER_KEY, BuildConfig.TWITTER_SECRET);
    Digits.Builder digitsBuilder = new Digits.Builder().withTheme(R.style.Digits_Theme);
       
    Fabric.with(this, new Crashlytics(), new TwitterCore(authConfig), digitsBuilder.build(), new Answers());

**Comment by arthtilva** [comment]
please write answer if you got solution.

**Comment by dudadayan** [comment]
+1

**Comment by malhobayyeb** [comment]
please write answer if you got solution.

**Comment by sillysachin** [comment]
+1

**Comment by mikebonnell** [comment]
Thank you for posting this issue and for the +1's. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
