### ISSUE TITLE
Digits sdk fails to use ActionBarActivity with recent appcompat version

### ISSUE THREAD

**Issue by brako** [crashlytics/digits-android#90]
Hello,

I tried to use a custom theme as explained in the documentation :

`dependencies {
	[...]
	compile 'com.android.support:appcompat-v7:25.1.1'
	[...]
}`

I have my custom theme :
`<style name="CustomDigitsTheme" parent="Theme.AppCompat.Light">
	<item name="android:textColorPrimary">@android:color/black</item>
	<item name="android:textColorSecondary">@android:color/darker_gray</item>
	<item name="android:windowBackground">@android:color/white</item>
	<item name="android:textColorLink">#ff398622</item>
	<item name="colorAccent">#ff398622</item>
</style>`

My button :
`private void setUpLoginButton() {
    mLoginButton.setAuthTheme(R.style.CustomDigitsTheme);
    [...]
}`

The theme works fine, but there is no Action bar in the screens. I looked into it, it seems that the the wrong activity is started.
For example the PhoneNumberActivity is started instead of the PhoneNumberActionBarActivity:
`ActivityManager: Displayed com.digits.sdk.android.PhoneNumberActivity`

The problem comes from the ActivityClassManagerFactory class, that fails to get field from the android.support.v7.appcompat.R$styleable class.
The field "Theme" doesn't exist in my appcompat-v7 version.

Any workaround for this ?
Thanks

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
