### ISSUE TITLE
Users can't login because a "Double verification code"

### ISSUE THREAD

**Issue by Max01010101010101** [crashlytics/digits-android#91]
For testing purposes i have logged in my Android app with Digits with different (real) phone numbers. After a couple of (successful) tries, Digit ask me for a  "Double verification code". 

What is a user supposed to do at the moment? Can we remove that "double verification" screen?

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
