### ISSUE TITLE
Re-Authentication not working

### ISSUE THREAD

**Issue by omuradil** [crashlytics/digits-android#93]
I'm having problems, the fact is that when I first logged in (sms came in with the code, went through the Authentication, and received a message in Toast "Authentication successful for").

But when the second time I try to open the page to fill the number, I press the button and I get again a message about successful authentication.

Code in onCreate method:

```
DigitsAuthButton digitsButton = (DigitsAuthButton) findViewById(R.id.auth_button);
        digitsButton.setCallback(new AuthCallback() {
            @Override
            public void success(DigitsSession session, String phoneNumber) {
                // TODO: associate the session userID with your user model
                Toast.makeText(getApplicationContext(), "Authentication successful for "
                        + phoneNumber, Toast.LENGTH_LONG).show();
            }

            @Override
            public void failure(DigitsException exception) {
                Log.d("Digits", "Sign in with Digits failure", exception);
            }
        });
```
Question: How do I clear a session or re-authorize?

**Comment by omuradil** [comment]
The method of Digits.logout () helped me. Although, in the documentation of this method was not written

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
