### ISSUE TITLE
Phone number field not focusable on Android 4.2

### ISSUE THREAD

**Issue by rostopira** [crashlytics/digits-android#94]
I've fixed identical bug in my project. Just replace EditText with AppCompatEditText

https://github.com/crashlytics/digits-android/blob/master/digits/src/main/res/layout/dgts__activity_phone_number.xml

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
