### ISSUE TITLE
How to remove button "use my phone number"?

### ISSUE THREAD

**Issue by omuradil** [crashlytics/digits-android#95]
How to immediately go to the number input, without pressing this button. I tried this option

    `AuthConfig.Builder builder = new AuthConfig.Builder();

        builder.withAuthCallBack(new AuthCallback() {
            @Override
            public void success(DigitsSession session, String phoneNumber) {
                TwitterAuthToken authToken = session.getAuthToken();
                Toast.makeText(getActivity(), "Authentication successful for "
                        + phoneNumber, Toast.LENGTH_LONG).show();
            }

            @Override
            public void failure(DigitsException error) {

            }
        });

        AuthConfig autConfig = builder.build();
        Digits.authenticate(autConfig);`

but it does not work. Can you tell me?

**Comment by mikebonnell** [comment]
Thank you for posting this issue. As the Digits SDK is evolving into [Firebase phone authentication](https://github.com/firebase/FirebaseUI-Android ) and being deprecated at the end of September, we don't plan on digging into this issue so I'm marking it as closed.

Firebase phone authentication includes the best of Digits plus more power, reliability and new features to drive user growth. [Learn more here!](http://get.digits.com/blog/introducing-firebase-phone-authentication
)
